<a href="https://colab.research.google.com/github/Shilajit-CR7/ML-Works/blob/main/NLTK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
import numpy as np
import pandas as pd

In [ ]:
from nltk.corpus import brown

In [ ]:
nltk.download('brown')

[nltk_data] Downloading package brown to C:\Users\Shilajit-
[nltk_data]     CR7\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!


True

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Shilajit-
[nltk_data]     CR7\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [ ]:
data = brown.sents(categories='romance')
data

[['They', 'neither', 'liked', 'nor', 'disliked', 'the', 'Old', 'Man', '.'], ['To', 'them', 'he', 'could', 'have', 'been', 'the', 'broken', 'bell', 'in', 'the', 'church', 'tower', 'which', 'rang', 'before', 'and', 'after', 'Mass', ',', 'and', 'at', 'noon', ',', 'and', 'at', 'six', 'each', 'evening', '--', 'its', 'tone', ',', 'repetitive', ',', 'monotonous', ',', 'never', 'breaking', 'the', 'boredom', 'of', 'the', 'streets', '.'], ...]

In [ ]:
' '.join(data[0])

'They neither liked nor disliked the Old Man .'

# Bag of Words Pipeline
1. Get the data
2. Tokenisation and stopword removal
3. Stemming
4. Builiding Vocab
5. Vectorization 
6. Classification

Tokenisation

In [ ]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [ ]:
document = "It was a very pleasant day. The weather was cool and there was light showers. I went to the market to buy some fruits."
sentence = "Send all the 50 documents related to chapters 1,2,3 at prateek@cb.com"

In [ ]:
sents = sent_tokenize(document)
# Breaks the document sentence by sentence
sents

['It was a very pleasant day.',
 'The weather was cool and there was light showers.',
 'I went to the market to buy some fruits.']

In [ ]:
words = word_tokenize(sentence)
# Breaks the document word by word 
words

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'prateek',
 '@',
 'cb.com']

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Shilajit-
[nltk_data]     CR7\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
sw = set(stopwords.words('english'))

In [ ]:
sw

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [ ]:
def remove_sw(text,sw):
    useful_words = [w for w in text if w not in sw]
    return useful_words

In [ ]:
text = "I was doing that.".split() # Always give word tokenized input
remove_sw(text,sw)

['I', 'that.']

Tokenization using Regular Expression 

In [ ]:
sentence = "Send all the 50 documents related to chapters 1,2,3 at prateek@cb.com"

In [ ]:
sentence.split()
# 1,2,3 or 50 is not tokenized. 
# Even with word_tokenize() we can't do this.
# so use regular exp tokenizer 

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'prateek@cb.com']

In [ ]:
from nltk.tokenize import RegexpTokenizer

In [ ]:
tokenizer = RegexpTokenizer('[a-zA-Z@]+')

In [ ]:
useful_text = tokenizer.tokenize(sentence)
useful_text

['Send',
 'all',
 'the',
 'documents',
 'related',
 'to',
 'chapters',
 'at',
 'prateek@cb',
 'com']

# Stemming
It actually tranforms the word into it's base format (ex: Running ==> Run)
Nltk provides 3 types of stemmer => 1. Snowball 2. Porter 3. Lancaster

In [ ]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [ ]:
ps = PorterStemmer()

In [ ]:
ps.stem('Running')

'run'

In [ ]:
ss = SnowballStemmer('english')
# Here you have to give the language as it supports other languages

In [ ]:
ss.stem(' I was Going')

' i was go'

In [ ]:
from nltk.stem import WordNetLemmatizer
wn = WordNetLemmatizer()
nltk.download('wordnet')
nltk.download('omw-1.4')
# Either stemming or lemmatiztion needed 

[nltk_data] Downloading package wordnet to C:\Users\Shilajit-
[nltk_data]     CR7\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Shilajit-
[nltk_data]     CR7\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
wn.lemmatize('Jumping')

'Jumping'

# Vectoriztion
- What word is coming how many times 
- Use sklearn CountVectorizer  

In [ ]:
corpus = [
    'Real Madrid wins the club world cup.',
    'Modi will win the elections.',
    'That man won hearts of the people.',
    'The movie Razzi is spy thriller'
]

In [ ]:
corpus

['Real Madrid wins the club world cup.',
 'Modi will win the elections.',
 'That man won hearts of the people.',
 'The movie Razzi is spy thriller']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
vect_corpus = cv.fit_transform(corpus)
vect_corpus

<4x22 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [ ]:
vect_corpus = vect_corpus.toarray()
vect_corpus

array([[1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0]],
      dtype=int64)

In [ ]:
cv.vocabulary_
# real : 12th idx
# wins : 19th idx

{'real': 12,
 'madrid': 5,
 'wins': 19,
 'the': 15,
 'club': 0,
 'world': 21,
 'cup': 1,
 'modi': 7,
 'will': 17,
 'win': 18,
 'elections': 2,
 'that': 14,
 'man': 6,
 'won': 20,
 'hearts': 3,
 'of': 9,
 'people': 10,
 'movie': 8,
 'razzi': 11,
 'is': 4,
 'spy': 13,
 'thriller': 16}

In [ ]:
s = cv.inverse_transform(vect_corpus[0].reshape(1, -1))
s
# From bag of words to sentece (inverse)

[array(['club', 'cup', 'madrid', 'real', 'the', 'wins', 'world'],
       dtype='<U9')]

# Vectorization with StopWord Removal

In [ ]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('[a-zA-Z@]+')

In [ ]:
def remove_sw(text,sw):
    useful_words = [w for w in text if w not in sw]
    return useful_words

In [ ]:
def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    words = remove_sw(words,sw)
    return words

In [ ]:
myTokenizer('This is some function')

['function']

In [ ]:
corpus

['Real Madrid wins the club world cup.',
 'Modi will win the elections.',
 'That man won hearts of the people.',
 'The movie Razzi is spy thriller']

In [ ]:
cv = CountVectorizer(tokenizer=myTokenizer)
vect_corpus = cv.fit_transform(corpus).toarray()

In [ ]:
vect_corpus

array([[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [ ]:
cv.inverse_transform(vect_corpus)

[array(['club', 'cup', 'madrid', 'real', 'wins', 'world'], dtype='<U9'),
 array(['elections', 'modi', 'win'], dtype='<U9'),
 array(['hearts', 'man', 'people'], dtype='<U9'),
 array(['movie', 'razzi', 'spy', 'thriller'], dtype='<U9')]

In [ ]:
# Traing data fit _transform. Test data only transform

# More Ways to Create Features 
- Unigram: Every word as a feature
- Bigrams
- Trigrams
- n-grams
- TF-IDF Normalisation

In [ ]:
s1 = ['This is a good movie.']
s2 = ['This is not a good movie.']
# s1 = good s2 = not good. Take 2 word features
# otherwise it will classify both s1 and s2 as good movies.

In [ ]:
cv = CountVectorizer(ngram_range=(2,2))
#(2,2) = two word feature 

In [ ]:
doc = [s1[0],s2[0]]
cv.fit_transform(doc).toarray()

array([[1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1]], dtype=int64)

In [ ]:
cv.vocabulary_
# 'this is' is one feature (two word feature --> bigrams)

{'this is': 4, 'is good': 1, 'good movie': 0, 'is not': 2, 'not good': 3}

In [ ]:
cv = CountVectorizer(ngram_range=(3,3))
doc = [s1[0],s2[0]]
cv.fit_transform(doc).toarray()

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]], dtype=int64)

In [ ]:
cv.vocabulary_
# 3 word feature. See n-word vectorizer find optimum n.

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

# TF-IDF

In [ ]:
s1 = 'this is good movie.'
s2 = 'this was good movie.'
s3 = 'this is not good movie.'

In [ ]:
corpus = [s1,s2,s3]

In [ ]:
corpus

['this is good movie.', 'this was good movie.', 'this is not good movie.']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [ ]:
vc  = tfidf.fit_transform(corpus).toarray()

In [ ]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}